[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicy = "on-failure"
maxRetries = 10
startTimeout = 600

[deploy.env]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["node --version", "npm --version"] 