[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "on-failure"
maxRetries = 5
startTimeout = 300

[deploy.env]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["node --version", "npm --version"]