services:
  - type: web
    name: formulario-visto-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 